# Rename to secrets.toml in Streamlit Cloud and set values in the dashboard
GROQ_API_KEY = "your_groq_api_key_here"
GROQ_MODEL = "llama-3.3-70b-versatile"
CHROMA_PERSIST_DIR = "./chroma_db"
EMBEDDINGS_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
